            - name: Auto Follows & Unfollows by Github Actions for Github users
  # You may pin to the exact commit or the version.
  # uses: Huniko519/Github-Auto-Follow-Unfollow-View-User-List@bf27ee1d502f77e9db6205b24bd694d992ef7a43
  uses: Huniko519/Github-Auto-Follow-Unfollow-View-User-List@v1.0.0
  with:
    # The token used to authenticate.
    token: # default is ${{ github.token }}
    # The base user name.
    username: # default is ${{ github.actor }}
    # The name of the repository.
    repository: # default is ${{ github.repository }}
          
