name: Auto Follows & Unfollows by Github Actions for Github users

on:
  # Define the event that triggers the workflow, e.g., push or pull_request
  push:
    branches:
      - main

jobs:
  follow-unfollow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Auto Follow and Unfollow
        uses: Huniko519/Github-Auto-Follow-Unfollow-View-User-List@bf27ee1d502f77e9db6205b24bd694d992ef7a43
        with:
          # The token used to authenticate.
          token: ${{ secrets.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 }}
          # The base user name.
          username: ${{ github.JophilGulane }}
          # The name of the repository.
          repository: ${{ github.calculator }}
